
[tool.poetry]
name = "arc_tools"
version = "0.1.0"
description = "Tools for the ARC dataset"
authors = ["மனோஜ்குமார் பழனிச்சாமி"]
packages = [
  { include = "arc_tools/**/*" },
]

[tool.poetry.dependencies]
python = "^3.10"


